# .kodiak.toml
version = 1

[merge]

method = "squash"

notify_on_conflict = false

dont_wait_on_status_checks = ["EIP Auto-Merge Bot", "Travis CI - Pull Request"]

require_automerge_label = false

# important
block_on_neutral_required_check_runs = true
